spring:
  application:
    name: springboot-gcp-api
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:}
      sql:
        enabled: ${GCP_SQL_ENABLED:false}
        database-name: ${GCP_DATABASE_NAME:}
        instance-connection-name: ${GCP_INSTANCE_CONNECTION_NAME:}

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.api: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: gcp
  
  datasource:
    url: jdbc:postgresql:///${GCP_DATABASE_NAME:springboot_db}?cloudSqlInstance=${GCP_INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
    username: ${GCP_DATABASE_USERNAME}
    password: ${GCP_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
  cloud:
    gcp:
      sql:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  
  h2:
    console:
      enabled: true
